In [1]:
import pandas as pd
import numpy as np

In [2]:
train = pd.read_table('train.tsv')
test = pd.read_table('test.tsv')

In [3]:
train.head()

sentence  label
0       hide new secretions from the parental units       0
1               contains no wit , only labored gags       0
2  that loves its characters and communicates som...      1
3  remains utterly satisfied to remain the same t...      0
4  on the worst revenge-of-the-nerds clichés the ...      0

In [4]:
test.head()

index                                           sentence
0      0             uneasy mishmash of styles and genres .
1      1  this film 's relationship to actual tension is...
2      2  by the end of no such thing the audience , lik...
3      3  director rob marshall went out gunning to make...
4      4  lathan and diggs have considerable personal ch...

In [5]:
X = np.c_[np.ones((train.shape[0], 1)), train]

In [6]:
X

array([[1.0, 'hide new secretions from the parental units ', 0],
       [1.0, 'contains no wit , only labored gags ', 0],
       [1.0,
        'that loves its characters and communicates something rather beautiful about human nature ',
        1],
       ...,
       [1.0,
        'at achieving the modest , crowd-pleasing goals it sets for itself ',
        1],
       [1.0, 'a patient viewer ', 1],
       [1.0,
        'this new jangle of noise , mayhem and stupidity must be a serious contender for the title . ',
        0]], dtype=object)

In [7]:
X.shape[1]

3

In [20]:
theta = np.zeros((X.shape[1], 1))

In [21]:
theta

array([[0.],
       [0.],
       [0.]])

In [23]:
from scipy.optimize import minimize, fmin_tnc
class mygradient():
    
    def __init__(self,n_iter = 10000, thres=1e-3):
        self.n_iter = n_iter
        self.thres = thres
        
    def get_theta(self):
        X = np.c_[np.ones((train.shape[0], 1)), train]
        theta = np.zeros((X.shape[1], 1))
        return theta
        
    
    def hypothesis(sel, X, theta):
        z = np.dot(X, theta)
        return 1/(1+np.exp(-(z)))


    def cost_function(self, theta, X, y):
        m = X.shape[0]
        y1 = hypothesis(X, theta)
        return -(1/len(X)) * np.sum(y*np.log(y1) + (1-y)*np.log(1-y1))


    def gradient(self, theta, X, y):
        m = X.shape[0]
        y1 = hypothesis(X, theta)
        return (1/m) * np.dot(X.T, y1 - y)

    def fit(self, X, y, theta):
        opt_weigths = fmin_tnc(func=self.cost_function, x0=theta,
                               fprime=gradient, args=(X, y.flatten()))
        return opt_weigths[0]


    def find_param(self, X, y, theta):
        y_uniq = list(set(y.flatten()))
        theta_list = []
        for i in y_uniq:
            y_tr = pd.Series(y_change(y, i))
            y_tr = y_tr[:, np.newaxis]
            theta1 = fit(X, y, theta)
            theta_list.append(theta1)
        return theta_list


    def predict(self, theta_list, x, y):
        y_uniq = list(set(y.flatten()))
        y_hat = [0]*len(y)
        for i in range(0, len(y_uniq)):
            y_tr = y_change(y, y_uniq[i])
            y1 = hypothesis(X, theta_list[i])
            for k in range(0, len(y)):
                if y_tr[k] == 1 and y1[k] >= 0.5:
                    y_hat[k] = y_uniq[i]
        return y_hat


    def accuracy(self): 
        accuracy=0
        for i in range(0, len(y)):
            if y_hat[i] == y.flatten()[i]:
                accuracy += 1
        acc = accuracy / len(df)*100
        return acc

In [24]:
model = mygradient()

In [26]:
model.get_theta()

array([[0.],
       [0.],
       [0.]])

In [28]:
model.hypothesis(X,theta)

TypeError: can't multiply sequence by non-int of type 'float'